/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions/$transactionId'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer/dashboard'
import { Route as OrganizerOrganizeIdRouteImport } from './routes/organizer/$organizeId'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as OrganizerDashboardIndexRouteImport } from './routes/organizer/dashboard.index'
import { Route as EventsSlugIndexRouteImport } from './routes/events/$slug.index'
import { Route as OrganizerDashboardTransactionsRouteImport } from './routes/organizer/dashboard.transactions'
import { Route as EventsSlugCheckoutRouteImport } from './routes/events/$slug.checkout'
import { Route as OrganizerDashboardEventsIndexRouteImport } from './routes/organizer/dashboard.events.index'
import { Route as OrganizerDashboardEventsNewRouteImport } from './routes/organizer/dashboard.events.new'
import { Route as OrganizerDashboardEventsEventIdVouchersRouteImport } from './routes/organizer/dashboard.events.$eventId.vouchers'
import { Route as OrganizerDashboardEventsEventIdEditRouteImport } from './routes/organizer/dashboard.events.$eventId.edit'
import { Route as OrganizerDashboardEventsEventIdAttendeesRouteImport } from './routes/organizer/dashboard.events.$eventId.attendees'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerOrganizeIdRoute = OrganizerOrganizeIdRouteImport.update({
  id: '/organizer/$organizeId',
  path: '/organizer/$organizeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerDashboardIndexRoute = OrganizerDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerDashboardRoute,
} as any)
const EventsSlugIndexRoute = EventsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsSlugRoute,
} as any)
const OrganizerDashboardTransactionsRoute =
  OrganizerDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)
const EventsSlugCheckoutRoute = EventsSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => EventsSlugRoute,
} as any)
const OrganizerDashboardEventsIndexRoute =
  OrganizerDashboardEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)
const OrganizerDashboardEventsNewRoute =
  OrganizerDashboardEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)
const OrganizerDashboardEventsEventIdVouchersRoute =
  OrganizerDashboardEventsEventIdVouchersRouteImport.update({
    id: '/events/$eventId/vouchers',
    path: '/events/$eventId/vouchers',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)
const OrganizerDashboardEventsEventIdEditRoute =
  OrganizerDashboardEventsEventIdEditRouteImport.update({
    id: '/events/$eventId/edit',
    path: '/events/$eventId/edit',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)
const OrganizerDashboardEventsEventIdAttendeesRoute =
  OrganizerDashboardEventsEventIdAttendeesRouteImport.update({
    id: '/events/$eventId/attendees',
    path: '/events/$eventId/attendees',
    getParentRoute: () => OrganizerDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/organizer/$organizeId': typeof OrganizerOrganizeIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRouteWithChildren
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/organizer/dashboard/transactions': typeof OrganizerDashboardTransactionsRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/organizer/dashboard/': typeof OrganizerDashboardIndexRoute
  '/organizer/dashboard/events/new': typeof OrganizerDashboardEventsNewRoute
  '/organizer/dashboard/events/': typeof OrganizerDashboardEventsIndexRoute
  '/organizer/dashboard/events/$eventId/attendees': typeof OrganizerDashboardEventsEventIdAttendeesRoute
  '/organizer/dashboard/events/$eventId/edit': typeof OrganizerDashboardEventsEventIdEditRoute
  '/organizer/dashboard/events/$eventId/vouchers': typeof OrganizerDashboardEventsEventIdVouchersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/organizer/$organizeId': typeof OrganizerOrganizeIdRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/events': typeof EventsIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/organizer/dashboard/transactions': typeof OrganizerDashboardTransactionsRoute
  '/events/$slug': typeof EventsSlugIndexRoute
  '/organizer/dashboard': typeof OrganizerDashboardIndexRoute
  '/organizer/dashboard/events/new': typeof OrganizerDashboardEventsNewRoute
  '/organizer/dashboard/events': typeof OrganizerDashboardEventsIndexRoute
  '/organizer/dashboard/events/$eventId/attendees': typeof OrganizerDashboardEventsEventIdAttendeesRoute
  '/organizer/dashboard/events/$eventId/edit': typeof OrganizerDashboardEventsEventIdEditRoute
  '/organizer/dashboard/events/$eventId/vouchers': typeof OrganizerDashboardEventsEventIdVouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/organizer/$organizeId': typeof OrganizerOrganizeIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRouteWithChildren
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/events/': typeof EventsIndexRoute
  '/events/$slug/checkout': typeof EventsSlugCheckoutRoute
  '/organizer/dashboard/transactions': typeof OrganizerDashboardTransactionsRoute
  '/events/$slug/': typeof EventsSlugIndexRoute
  '/organizer/dashboard/': typeof OrganizerDashboardIndexRoute
  '/organizer/dashboard/events/new': typeof OrganizerDashboardEventsNewRoute
  '/organizer/dashboard/events/': typeof OrganizerDashboardEventsIndexRoute
  '/organizer/dashboard/events/$eventId/attendees': typeof OrganizerDashboardEventsEventIdAttendeesRoute
  '/organizer/dashboard/events/$eventId/edit': typeof OrganizerDashboardEventsEventIdEditRoute
  '/organizer/dashboard/events/$eventId/vouchers': typeof OrganizerDashboardEventsEventIdVouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/events/$slug'
    | '/organizer/$organizeId'
    | '/organizer/dashboard'
    | '/transactions/$transactionId'
    | '/events/'
    | '/events/$slug/checkout'
    | '/organizer/dashboard/transactions'
    | '/events/$slug/'
    | '/organizer/dashboard/'
    | '/organizer/dashboard/events/new'
    | '/organizer/dashboard/events/'
    | '/organizer/dashboard/events/$eventId/attendees'
    | '/organizer/dashboard/events/$eventId/edit'
    | '/organizer/dashboard/events/$eventId/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/organizer/$organizeId'
    | '/transactions/$transactionId'
    | '/events'
    | '/events/$slug/checkout'
    | '/organizer/dashboard/transactions'
    | '/events/$slug'
    | '/organizer/dashboard'
    | '/organizer/dashboard/events/new'
    | '/organizer/dashboard/events'
    | '/organizer/dashboard/events/$eventId/attendees'
    | '/organizer/dashboard/events/$eventId/edit'
    | '/organizer/dashboard/events/$eventId/vouchers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/events/$slug'
    | '/organizer/$organizeId'
    | '/organizer/dashboard'
    | '/transactions/$transactionId'
    | '/events/'
    | '/events/$slug/checkout'
    | '/organizer/dashboard/transactions'
    | '/events/$slug/'
    | '/organizer/dashboard/'
    | '/organizer/dashboard/events/new'
    | '/organizer/dashboard/events/'
    | '/organizer/dashboard/events/$eventId/attendees'
    | '/organizer/dashboard/events/$eventId/edit'
    | '/organizer/dashboard/events/$eventId/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
  OrganizerOrganizeIdRoute: typeof OrganizerOrganizeIdRoute
  OrganizerDashboardRoute: typeof OrganizerDashboardRouteWithChildren
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$organizeId': {
      id: '/organizer/$organizeId'
      path: '/organizer/$organizeId'
      fullPath: '/organizer/$organizeId'
      preLoaderRoute: typeof OrganizerOrganizeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/dashboard/': {
      id: '/organizer/dashboard/'
      path: '/'
      fullPath: '/organizer/dashboard/'
      preLoaderRoute: typeof OrganizerDashboardIndexRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/events/$slug/': {
      id: '/events/$slug/'
      path: '/'
      fullPath: '/events/$slug/'
      preLoaderRoute: typeof EventsSlugIndexRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/organizer/dashboard/transactions': {
      id: '/organizer/dashboard/transactions'
      path: '/transactions'
      fullPath: '/organizer/dashboard/transactions'
      preLoaderRoute: typeof OrganizerDashboardTransactionsRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/events/$slug/checkout': {
      id: '/events/$slug/checkout'
      path: '/checkout'
      fullPath: '/events/$slug/checkout'
      preLoaderRoute: typeof EventsSlugCheckoutRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/organizer/dashboard/events/': {
      id: '/organizer/dashboard/events/'
      path: '/events'
      fullPath: '/organizer/dashboard/events/'
      preLoaderRoute: typeof OrganizerDashboardEventsIndexRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/organizer/dashboard/events/new': {
      id: '/organizer/dashboard/events/new'
      path: '/events/new'
      fullPath: '/organizer/dashboard/events/new'
      preLoaderRoute: typeof OrganizerDashboardEventsNewRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/organizer/dashboard/events/$eventId/vouchers': {
      id: '/organizer/dashboard/events/$eventId/vouchers'
      path: '/events/$eventId/vouchers'
      fullPath: '/organizer/dashboard/events/$eventId/vouchers'
      preLoaderRoute: typeof OrganizerDashboardEventsEventIdVouchersRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/organizer/dashboard/events/$eventId/edit': {
      id: '/organizer/dashboard/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/organizer/dashboard/events/$eventId/edit'
      preLoaderRoute: typeof OrganizerDashboardEventsEventIdEditRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
    '/organizer/dashboard/events/$eventId/attendees': {
      id: '/organizer/dashboard/events/$eventId/attendees'
      path: '/events/$eventId/attendees'
      fullPath: '/organizer/dashboard/events/$eventId/attendees'
      preLoaderRoute: typeof OrganizerDashboardEventsEventIdAttendeesRouteImport
      parentRoute: typeof OrganizerDashboardRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugCheckoutRoute: typeof EventsSlugCheckoutRoute
  EventsSlugIndexRoute: typeof EventsSlugIndexRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugCheckoutRoute: EventsSlugCheckoutRoute,
  EventsSlugIndexRoute: EventsSlugIndexRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

interface OrganizerDashboardRouteChildren {
  OrganizerDashboardTransactionsRoute: typeof OrganizerDashboardTransactionsRoute
  OrganizerDashboardIndexRoute: typeof OrganizerDashboardIndexRoute
  OrganizerDashboardEventsNewRoute: typeof OrganizerDashboardEventsNewRoute
  OrganizerDashboardEventsIndexRoute: typeof OrganizerDashboardEventsIndexRoute
  OrganizerDashboardEventsEventIdAttendeesRoute: typeof OrganizerDashboardEventsEventIdAttendeesRoute
  OrganizerDashboardEventsEventIdEditRoute: typeof OrganizerDashboardEventsEventIdEditRoute
  OrganizerDashboardEventsEventIdVouchersRoute: typeof OrganizerDashboardEventsEventIdVouchersRoute
}

const OrganizerDashboardRouteChildren: OrganizerDashboardRouteChildren = {
  OrganizerDashboardTransactionsRoute: OrganizerDashboardTransactionsRoute,
  OrganizerDashboardIndexRoute: OrganizerDashboardIndexRoute,
  OrganizerDashboardEventsNewRoute: OrganizerDashboardEventsNewRoute,
  OrganizerDashboardEventsIndexRoute: OrganizerDashboardEventsIndexRoute,
  OrganizerDashboardEventsEventIdAttendeesRoute:
    OrganizerDashboardEventsEventIdAttendeesRoute,
  OrganizerDashboardEventsEventIdEditRoute:
    OrganizerDashboardEventsEventIdEditRoute,
  OrganizerDashboardEventsEventIdVouchersRoute:
    OrganizerDashboardEventsEventIdVouchersRoute,
}

const OrganizerDashboardRouteWithChildren =
  OrganizerDashboardRoute._addFileChildren(OrganizerDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  EventsSlugRoute: EventsSlugRouteWithChildren,
  OrganizerOrganizeIdRoute: OrganizerOrganizeIdRoute,
  OrganizerDashboardRoute: OrganizerDashboardRouteWithChildren,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
